[2018-03-31 11:59:24] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:00:22] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:00:22] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:00:22] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:00:34] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:00:34] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:00:34] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:00:34] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:13:25] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:13:26] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:13:26] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:13:26] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:13:57] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:13:58] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:13:58] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:15:00] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:15:00] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:15:01] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:16:39] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:16:39] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:16:39] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:16:49] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:16:49] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:16:49] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:17:51] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:17:51] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:17:52] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:18:04] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:18:04] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:18:04] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:18:22] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:18:22] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:18:23] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:21:54] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:21:54] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:21:54] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:22:54] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:22:54] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:22:54] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:23:19] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:23:45] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:23:45] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:23:45] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:24:21] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:24:21] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:24:21] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:24:43] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:24:43] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:24:43] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:25:12] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:25:12] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:25:12] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:42:32] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:42:32] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:42:32] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:42:47] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:42:48] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:42:48] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:42:53] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:42:53] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:42:54] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:53:00] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:53:00] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:53:00] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:53:49] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:53:49] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:53:49] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:54:02] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:54:02] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:54:02] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:54:36] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:54:36] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:54:36] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:54:46] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:54:46] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:54:47] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:54:57] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:54:57] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:54:57] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:55:00] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:55:00] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:55:00] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:55:08] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:55:09] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 12:55:09] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:03:42] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:03:42] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:03:42] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:05:36] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:05:36] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:05:36] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:05:57] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:05:57] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:05:57] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:17:08] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:19:26] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:19:30] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:20:04] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:20:05] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:20:25] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:20:26] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:20:37] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:20:38] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:20:40] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:20:50] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:20:51] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:20:51] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:20:52] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:20:52] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:21:37] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:21:37] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:21:37] local.ERROR: PDOException: SQLSTATE[HY000]: General error: -804 Incorrect values within SQLDA structure empty pointer to NULL indicator variable at SQLVAR index 0  in C:\xampp\htdocs\app\Models\Conexao\_Conexao.php:105
Stack trace:
#0 C:\xampp\htdocs\app\Models\Conexao\_Conexao.php(105): PDO->query('\n              ...')
#1 C:\xampp\htdocs\app\Models\DAO\Menu\MenuDAO.php(134): App\Models\Conexao\_Conexao->query('\n              ...')
#2 C:\xampp\htdocs\app\Models\DTO\Menu\Menu.php(69): App\Models\DAO\Menu\MenuDAO::selectMenu()
#3 C:\xampp\htdocs\app\Http\Controllers\Menu\MenuController.php(117): App\Models\DTO\Menu\Menu::selectMenu()
#4 [internal function]: App\Http\Controllers\Menu\MenuController->listarMenu()
#5 C:\xampp\htdocs\bootstrap\cache\compiled.php(8909): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\bootstrap\cache\compiled.php(8978): Illuminate\Routing\Controller->callAction('listarMenu', Array)
#7 C:\xampp\htdocs\bootstrap\cache\compiled.php(8958): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), 'listarMenu')
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\bootstrap\cache\compiled.php(8959): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 C:\xampp\htdocs\bootstrap\cache\compiled.php(8944): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'listarMenu')
#14 C:\xampp\htdocs\bootstrap\cache\compiled.php(7889): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'listarMenu')
#15 C:\xampp\htdocs\bootstrap\cache\compiled.php(7860): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\bootstrap\cache\compiled.php(7513): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\bootstrap\cache\compiled.php(7514): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 C:\xampp\htdocs\bootstrap\cache\compiled.php(7502): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\bootstrap\cache\compiled.php(7487): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\bootstrap\cache\compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\bootstrap\cache\compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#33 C:\xampp\htdocs\bootstrap\cache\compiled.php(12980): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#36 C:\xampp\htdocs\bootstrap\cache\compiled.php(11572): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#39 C:\xampp\htdocs\bootstrap\cache\compiled.php(12717): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#42 C:\xampp\htdocs\bootstrap\cache\compiled.php(12654): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#45 C:\xampp\htdocs\bootstrap\cache\compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\xampp\htdocs\bootstrap\cache\compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 C:\xampp\htdocs\bootstrap\cache\compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}  
[2018-03-31 13:22:00] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:22:00] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:22:00] local.ERROR: PDOException: SQLSTATE[HY000]: General error: -804 Incorrect values within SQLDA structure empty pointer to NULL indicator variable at SQLVAR index 0  in C:\xampp\htdocs\app\Models\Conexao\_Conexao.php:105
Stack trace:
#0 C:\xampp\htdocs\app\Models\Conexao\_Conexao.php(105): PDO->query('\n              ...')
#1 C:\xampp\htdocs\app\Models\DAO\Menu\MenuDAO.php(134): App\Models\Conexao\_Conexao->query('\n              ...')
#2 C:\xampp\htdocs\app\Models\DTO\Menu\Menu.php(69): App\Models\DAO\Menu\MenuDAO::selectMenu()
#3 C:\xampp\htdocs\app\Http\Controllers\Menu\MenuController.php(117): App\Models\DTO\Menu\Menu::selectMenu()
#4 [internal function]: App\Http\Controllers\Menu\MenuController->listarMenu()
#5 C:\xampp\htdocs\bootstrap\cache\compiled.php(8909): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\bootstrap\cache\compiled.php(8978): Illuminate\Routing\Controller->callAction('listarMenu', Array)
#7 C:\xampp\htdocs\bootstrap\cache\compiled.php(8958): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), 'listarMenu')
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\bootstrap\cache\compiled.php(8959): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 C:\xampp\htdocs\bootstrap\cache\compiled.php(8944): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'listarMenu')
#14 C:\xampp\htdocs\bootstrap\cache\compiled.php(7889): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'listarMenu')
#15 C:\xampp\htdocs\bootstrap\cache\compiled.php(7860): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\bootstrap\cache\compiled.php(7513): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\bootstrap\cache\compiled.php(7514): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 C:\xampp\htdocs\bootstrap\cache\compiled.php(7502): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\bootstrap\cache\compiled.php(7487): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\bootstrap\cache\compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\bootstrap\cache\compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#33 C:\xampp\htdocs\bootstrap\cache\compiled.php(12980): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#36 C:\xampp\htdocs\bootstrap\cache\compiled.php(11572): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#39 C:\xampp\htdocs\bootstrap\cache\compiled.php(12717): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#42 C:\xampp\htdocs\bootstrap\cache\compiled.php(12654): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#45 C:\xampp\htdocs\bootstrap\cache\compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\xampp\htdocs\bootstrap\cache\compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 C:\xampp\htdocs\bootstrap\cache\compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}  
[2018-03-31 13:22:25] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:22:25] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:22:25] local.ERROR: PDOException: SQLSTATE[HY000]: General error: -804 Incorrect values within SQLDA structure empty pointer to NULL indicator variable at SQLVAR index 0  in C:\xampp\htdocs\app\Models\Conexao\_Conexao.php:105
Stack trace:
#0 C:\xampp\htdocs\app\Models\Conexao\_Conexao.php(105): PDO->query('\n              ...')
#1 C:\xampp\htdocs\app\Models\DAO\Menu\MenuDAO.php(134): App\Models\Conexao\_Conexao->query('\n              ...')
#2 C:\xampp\htdocs\app\Models\DTO\Menu\Menu.php(69): App\Models\DAO\Menu\MenuDAO::selectMenu()
#3 C:\xampp\htdocs\app\Http\Controllers\Menu\MenuController.php(117): App\Models\DTO\Menu\Menu::selectMenu()
#4 [internal function]: App\Http\Controllers\Menu\MenuController->listarMenu()
#5 C:\xampp\htdocs\bootstrap\cache\compiled.php(8909): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\bootstrap\cache\compiled.php(8978): Illuminate\Routing\Controller->callAction('listarMenu', Array)
#7 C:\xampp\htdocs\bootstrap\cache\compiled.php(8958): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), 'listarMenu')
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\bootstrap\cache\compiled.php(8959): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 C:\xampp\htdocs\bootstrap\cache\compiled.php(8944): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'listarMenu')
#14 C:\xampp\htdocs\bootstrap\cache\compiled.php(7889): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'listarMenu')
#15 C:\xampp\htdocs\bootstrap\cache\compiled.php(7860): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\bootstrap\cache\compiled.php(7513): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\bootstrap\cache\compiled.php(7514): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 C:\xampp\htdocs\bootstrap\cache\compiled.php(7502): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\bootstrap\cache\compiled.php(7487): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\bootstrap\cache\compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\bootstrap\cache\compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#33 C:\xampp\htdocs\bootstrap\cache\compiled.php(12980): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#36 C:\xampp\htdocs\bootstrap\cache\compiled.php(11572): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#39 C:\xampp\htdocs\bootstrap\cache\compiled.php(12717): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#42 C:\xampp\htdocs\bootstrap\cache\compiled.php(12654): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#45 C:\xampp\htdocs\bootstrap\cache\compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\xampp\htdocs\bootstrap\cache\compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 C:\xampp\htdocs\bootstrap\cache\compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}  
[2018-03-31 13:22:40] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:22:40] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:22:40] local.ERROR: PDOException: SQLSTATE[HY000]: General error: -804 Incorrect values within SQLDA structure empty pointer to NULL indicator variable at SQLVAR index 0  in C:\xampp\htdocs\app\Models\Conexao\_Conexao.php:105
Stack trace:
#0 C:\xampp\htdocs\app\Models\Conexao\_Conexao.php(105): PDO->query('\n              ...')
#1 C:\xampp\htdocs\app\Models\DAO\Menu\MenuDAO.php(134): App\Models\Conexao\_Conexao->query('\n              ...')
#2 C:\xampp\htdocs\app\Models\DTO\Menu\Menu.php(69): App\Models\DAO\Menu\MenuDAO::selectMenu()
#3 C:\xampp\htdocs\app\Http\Controllers\Menu\MenuController.php(117): App\Models\DTO\Menu\Menu::selectMenu()
#4 [internal function]: App\Http\Controllers\Menu\MenuController->listarMenu()
#5 C:\xampp\htdocs\bootstrap\cache\compiled.php(8909): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\bootstrap\cache\compiled.php(8978): Illuminate\Routing\Controller->callAction('listarMenu', Array)
#7 C:\xampp\htdocs\bootstrap\cache\compiled.php(8958): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), 'listarMenu')
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\bootstrap\cache\compiled.php(8959): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 C:\xampp\htdocs\bootstrap\cache\compiled.php(8944): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'listarMenu')
#14 C:\xampp\htdocs\bootstrap\cache\compiled.php(7889): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'listarMenu')
#15 C:\xampp\htdocs\bootstrap\cache\compiled.php(7860): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\bootstrap\cache\compiled.php(7513): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\bootstrap\cache\compiled.php(7514): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 C:\xampp\htdocs\bootstrap\cache\compiled.php(7502): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\bootstrap\cache\compiled.php(7487): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\bootstrap\cache\compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\bootstrap\cache\compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#33 C:\xampp\htdocs\bootstrap\cache\compiled.php(12980): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#36 C:\xampp\htdocs\bootstrap\cache\compiled.php(11572): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#39 C:\xampp\htdocs\bootstrap\cache\compiled.php(12717): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#42 C:\xampp\htdocs\bootstrap\cache\compiled.php(12654): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#45 C:\xampp\htdocs\bootstrap\cache\compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\xampp\htdocs\bootstrap\cache\compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 C:\xampp\htdocs\bootstrap\cache\compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}  
[2018-03-31 13:23:02] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:23:02] local.ERROR: PDOException: SQLSTATE[HY000]: General error: -804 Incorrect values within SQLDA structure empty pointer to NULL indicator variable at SQLVAR index 0  in C:\xampp\htdocs\app\Models\Conexao\_Conexao.php:105
Stack trace:
#0 C:\xampp\htdocs\app\Models\Conexao\_Conexao.php(105): PDO->query('\n              ...')
#1 C:\xampp\htdocs\app\Models\DAO\Menu\MenuDAO.php(134): App\Models\Conexao\_Conexao->query('\n              ...')
#2 C:\xampp\htdocs\app\Models\DTO\Menu\Menu.php(69): App\Models\DAO\Menu\MenuDAO::selectMenu()
#3 C:\xampp\htdocs\app\Http\Controllers\Menu\MenuController.php(117): App\Models\DTO\Menu\Menu::selectMenu()
#4 [internal function]: App\Http\Controllers\Menu\MenuController->listarMenu()
#5 C:\xampp\htdocs\bootstrap\cache\compiled.php(8909): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\bootstrap\cache\compiled.php(8978): Illuminate\Routing\Controller->callAction('listarMenu', Array)
#7 C:\xampp\htdocs\bootstrap\cache\compiled.php(8958): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), 'listarMenu')
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\bootstrap\cache\compiled.php(8959): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 C:\xampp\htdocs\bootstrap\cache\compiled.php(8944): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'listarMenu')
#14 C:\xampp\htdocs\bootstrap\cache\compiled.php(7889): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'listarMenu')
#15 C:\xampp\htdocs\bootstrap\cache\compiled.php(7860): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\bootstrap\cache\compiled.php(7513): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\bootstrap\cache\compiled.php(7514): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 C:\xampp\htdocs\bootstrap\cache\compiled.php(7502): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\bootstrap\cache\compiled.php(7487): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\bootstrap\cache\compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\bootstrap\cache\compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#33 C:\xampp\htdocs\bootstrap\cache\compiled.php(12980): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#36 C:\xampp\htdocs\bootstrap\cache\compiled.php(11572): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#39 C:\xampp\htdocs\bootstrap\cache\compiled.php(12717): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#42 C:\xampp\htdocs\bootstrap\cache\compiled.php(12654): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#45 C:\xampp\htdocs\bootstrap\cache\compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\xampp\htdocs\bootstrap\cache\compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 C:\xampp\htdocs\bootstrap\cache\compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}  
[2018-03-31 13:23:02] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:23:19] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:23:19] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:23:19] local.ERROR: PDOException: SQLSTATE[HY000]: General error: -804 Incorrect values within SQLDA structure empty pointer to NULL indicator variable at SQLVAR index 0  in C:\xampp\htdocs\app\Models\Conexao\_Conexao.php:105
Stack trace:
#0 C:\xampp\htdocs\app\Models\Conexao\_Conexao.php(105): PDO->query('\n              ...')
#1 C:\xampp\htdocs\app\Models\DAO\Menu\MenuDAO.php(134): App\Models\Conexao\_Conexao->query('\n              ...')
#2 C:\xampp\htdocs\app\Models\DTO\Menu\Menu.php(69): App\Models\DAO\Menu\MenuDAO::selectMenu()
#3 C:\xampp\htdocs\app\Http\Controllers\Menu\MenuController.php(117): App\Models\DTO\Menu\Menu::selectMenu()
#4 [internal function]: App\Http\Controllers\Menu\MenuController->listarMenu()
#5 C:\xampp\htdocs\bootstrap\cache\compiled.php(8909): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\bootstrap\cache\compiled.php(8978): Illuminate\Routing\Controller->callAction('listarMenu', Array)
#7 C:\xampp\htdocs\bootstrap\cache\compiled.php(8958): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), 'listarMenu')
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\bootstrap\cache\compiled.php(8959): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 C:\xampp\htdocs\bootstrap\cache\compiled.php(8944): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'listarMenu')
#14 C:\xampp\htdocs\bootstrap\cache\compiled.php(7889): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'listarMenu')
#15 C:\xampp\htdocs\bootstrap\cache\compiled.php(7860): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\bootstrap\cache\compiled.php(7513): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\bootstrap\cache\compiled.php(7514): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 C:\xampp\htdocs\bootstrap\cache\compiled.php(7502): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\bootstrap\cache\compiled.php(7487): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\bootstrap\cache\compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\bootstrap\cache\compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#33 C:\xampp\htdocs\bootstrap\cache\compiled.php(12980): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#36 C:\xampp\htdocs\bootstrap\cache\compiled.php(11572): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#39 C:\xampp\htdocs\bootstrap\cache\compiled.php(12717): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#42 C:\xampp\htdocs\bootstrap\cache\compiled.php(12654): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#45 C:\xampp\htdocs\bootstrap\cache\compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\xampp\htdocs\bootstrap\cache\compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 C:\xampp\htdocs\bootstrap\cache\compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}  
[2018-03-31 13:24:13] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:24:13] local.ERROR: PDOException: SQLSTATE[HY000]: General error: -804 Incorrect values within SQLDA structure empty pointer to NULL indicator variable at SQLVAR index 0  in C:\xampp\htdocs\app\Models\Conexao\_Conexao.php:105
Stack trace:
#0 C:\xampp\htdocs\app\Models\Conexao\_Conexao.php(105): PDO->query('\n              ...')
#1 C:\xampp\htdocs\app\Models\DAO\Menu\MenuDAO.php(134): App\Models\Conexao\_Conexao->query('\n              ...')
#2 C:\xampp\htdocs\app\Models\DTO\Menu\Menu.php(69): App\Models\DAO\Menu\MenuDAO::selectMenu()
#3 C:\xampp\htdocs\app\Http\Controllers\Menu\MenuController.php(117): App\Models\DTO\Menu\Menu::selectMenu()
#4 [internal function]: App\Http\Controllers\Menu\MenuController->listarMenu()
#5 C:\xampp\htdocs\bootstrap\cache\compiled.php(8909): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\bootstrap\cache\compiled.php(8978): Illuminate\Routing\Controller->callAction('listarMenu', Array)
#7 C:\xampp\htdocs\bootstrap\cache\compiled.php(8958): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), 'listarMenu')
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\bootstrap\cache\compiled.php(8959): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 C:\xampp\htdocs\bootstrap\cache\compiled.php(8944): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'listarMenu')
#14 C:\xampp\htdocs\bootstrap\cache\compiled.php(7889): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'listarMenu')
#15 C:\xampp\htdocs\bootstrap\cache\compiled.php(7860): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\bootstrap\cache\compiled.php(7513): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\bootstrap\cache\compiled.php(7514): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 C:\xampp\htdocs\bootstrap\cache\compiled.php(7502): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\bootstrap\cache\compiled.php(7487): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\bootstrap\cache\compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\bootstrap\cache\compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#33 C:\xampp\htdocs\bootstrap\cache\compiled.php(12980): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#36 C:\xampp\htdocs\bootstrap\cache\compiled.php(11572): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#39 C:\xampp\htdocs\bootstrap\cache\compiled.php(12717): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#42 C:\xampp\htdocs\bootstrap\cache\compiled.php(12654): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#45 C:\xampp\htdocs\bootstrap\cache\compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\xampp\htdocs\bootstrap\cache\compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 C:\xampp\htdocs\bootstrap\cache\compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}  
[2018-03-31 13:24:14] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:26:04] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:26:05] local.INFO: ADMIN      | 127.0.0.1     | Array
(
    [:USUARIO_ID] => 1
)
  
[2018-03-31 13:26:05] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:26:05] local.ERROR: PDOException: SQLSTATE[HY000]: General error: -804 Incorrect values within SQLDA structure empty pointer to NULL indicator variable at SQLVAR index 0  in C:\xampp\htdocs\app\Models\Conexao\_Conexao.php:105
Stack trace:
#0 C:\xampp\htdocs\app\Models\Conexao\_Conexao.php(105): PDO->query('\n              ...')
#1 C:\xampp\htdocs\app\Models\DAO\Menu\MenuDAO.php(136): App\Models\Conexao\_Conexao->query('\n              ...')
#2 C:\xampp\htdocs\app\Models\DTO\Menu\Menu.php(69): App\Models\DAO\Menu\MenuDAO::selectMenu()
#3 C:\xampp\htdocs\app\Http\Controllers\Menu\MenuController.php(117): App\Models\DTO\Menu\Menu::selectMenu()
#4 [internal function]: App\Http\Controllers\Menu\MenuController->listarMenu()
#5 C:\xampp\htdocs\bootstrap\cache\compiled.php(8909): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\bootstrap\cache\compiled.php(8978): Illuminate\Routing\Controller->callAction('listarMenu', Array)
#7 C:\xampp\htdocs\bootstrap\cache\compiled.php(8958): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), 'listarMenu')
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\bootstrap\cache\compiled.php(8959): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 C:\xampp\htdocs\bootstrap\cache\compiled.php(8944): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Menu\MenuController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'listarMenu')
#14 C:\xampp\htdocs\bootstrap\cache\compiled.php(7889): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'listarMenu')
#15 C:\xampp\htdocs\bootstrap\cache\compiled.php(7860): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\bootstrap\cache\compiled.php(7513): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\bootstrap\cache\compiled.php(7514): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 C:\xampp\htdocs\bootstrap\cache\compiled.php(7502): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\bootstrap\cache\compiled.php(7487): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\bootstrap\cache\compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 C:\xampp\htdocs\bootstrap\cache\compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\bootstrap\cache\compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#33 C:\xampp\htdocs\bootstrap\cache\compiled.php(12980): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#36 C:\xampp\htdocs\bootstrap\cache\compiled.php(11572): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#39 C:\xampp\htdocs\bootstrap\cache\compiled.php(12717): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#42 C:\xampp\htdocs\bootstrap\cache\compiled.php(12654): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#45 C:\xampp\htdocs\bootstrap\cache\compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\xampp\htdocs\bootstrap\cache\compiled.php(9621): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\xampp\htdocs\bootstrap\cache\compiled.php(9611): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\xampp\htdocs\bootstrap\cache\compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 C:\xampp\htdocs\bootstrap\cache\compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}  
[2018-03-31 13:27:45] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:27:45] local.INFO: ADMIN      | 127.0.0.1     | Teste44  
[2018-03-31 13:27:45] local.INFO: ADMIN      | 127.0.0.1     | Teste5  
[2018-03-31 13:28:36] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:29:25] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:29:28] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:29:35] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:29:36] local.INFO: ADMIN      | 127.0.0.1     | Teste44  
[2018-03-31 13:29:36] local.INFO: ADMIN      | 127.0.0.1     | Teste5  
[2018-03-31 13:30:22] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:31:02] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:32:04] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:32:08] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:32:15] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:32:15] local.INFO: ADMIN      | 127.0.0.1     | Teste44  
[2018-03-31 13:32:15] local.INFO: ADMIN      | 127.0.0.1     | Teste5  
[2018-03-31 13:33:38] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:34:42] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:34:42] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:34:42] local.ERROR: InvalidArgumentException: View [errors.500] not found. in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 C:\xampp\htdocs\bootstrap\cache\compiled.php(13963): Illuminate\View\FileViewFinder->findInPaths('errors.500', Array)
#1 C:\xampp\htdocs\bootstrap\cache\compiled.php(14091): Illuminate\View\FileViewFinder->find('errors.500')
#2 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(71): Illuminate\View\Factory->make('errors.500', Array)
#3 C:\xampp\htdocs\app\Exceptions\Handler.php(156): Illuminate\Routing\ResponseFactory->view('errors.500', Array, 500)
#4 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(143): App\Exceptions\Handler->convertExceptionToResponse(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#5 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(96): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#6 C:\xampp\htdocs\app\Exceptions\Handler.php(82): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#7 C:\xampp\htdocs\bootstrap\cache\compiled.php(2327): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#8 C:\xampp\htdocs\bootstrap\cache\compiled.php(2243): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#9 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#10 {main}  
[2018-03-31 13:34:42] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:34:42] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught InvalidArgumentException: View [errors.500] not found. in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 C:\xampp\htdocs\bootstrap\cache\compiled.php(13963): Illuminate\View\FileViewFinder->findInPaths('errors.500', Array)
#1 C:\xampp\htdocs\bootstrap\cache\compiled.php(14091): Illuminate\View\FileViewFinder->find('errors.500')
#2 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(71): Illuminate\View\Factory->make('errors.500', Array)
#3 C:\xampp\htdocs\app\Exceptions\Handler.php(156): Illuminate\Routing\ResponseFactory->view('errors.500', Array, 500)
#4 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(98): App\Exceptions\Handler->convertExceptionToResponse(Object(InvalidArgumentException))
#5 C:\xampp\htdocs\app\Exceptions\Handler.php(82): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(InvalidArgumentException))
#6 C:\xampp\htdocs\bootstrap\cache\compiled.php(2084) in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 {main}  
[2018-03-31 13:34:45] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:34:45] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:34:45] local.ERROR: InvalidArgumentException: View [errors.500] not found. in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 C:\xampp\htdocs\bootstrap\cache\compiled.php(13963): Illuminate\View\FileViewFinder->findInPaths('errors.500', Array)
#1 C:\xampp\htdocs\bootstrap\cache\compiled.php(14091): Illuminate\View\FileViewFinder->find('errors.500')
#2 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(71): Illuminate\View\Factory->make('errors.500', Array)
#3 C:\xampp\htdocs\app\Exceptions\Handler.php(156): Illuminate\Routing\ResponseFactory->view('errors.500', Array, 500)
#4 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(143): App\Exceptions\Handler->convertExceptionToResponse(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#5 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(96): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#6 C:\xampp\htdocs\app\Exceptions\Handler.php(82): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#7 C:\xampp\htdocs\bootstrap\cache\compiled.php(2327): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#8 C:\xampp\htdocs\bootstrap\cache\compiled.php(2243): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#9 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#10 {main}  
[2018-03-31 13:34:45] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:34:45] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught InvalidArgumentException: View [errors.500] not found. in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 C:\xampp\htdocs\bootstrap\cache\compiled.php(13963): Illuminate\View\FileViewFinder->findInPaths('errors.500', Array)
#1 C:\xampp\htdocs\bootstrap\cache\compiled.php(14091): Illuminate\View\FileViewFinder->find('errors.500')
#2 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(71): Illuminate\View\Factory->make('errors.500', Array)
#3 C:\xampp\htdocs\app\Exceptions\Handler.php(156): Illuminate\Routing\ResponseFactory->view('errors.500', Array, 500)
#4 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(98): App\Exceptions\Handler->convertExceptionToResponse(Object(InvalidArgumentException))
#5 C:\xampp\htdocs\app\Exceptions\Handler.php(82): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(InvalidArgumentException))
#6 C:\xampp\htdocs\bootstrap\cache\compiled.php(2084) in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 {main}  
[2018-03-31 13:34:52] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:34:52] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:34:52] local.ERROR: InvalidArgumentException: View [errors.500] not found. in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 C:\xampp\htdocs\bootstrap\cache\compiled.php(13963): Illuminate\View\FileViewFinder->findInPaths('errors.500', Array)
#1 C:\xampp\htdocs\bootstrap\cache\compiled.php(14091): Illuminate\View\FileViewFinder->find('errors.500')
#2 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(71): Illuminate\View\Factory->make('errors.500', Array)
#3 C:\xampp\htdocs\app\Exceptions\Handler.php(156): Illuminate\Routing\ResponseFactory->view('errors.500', Array, 500)
#4 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(143): App\Exceptions\Handler->convertExceptionToResponse(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#5 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(96): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#6 C:\xampp\htdocs\app\Exceptions\Handler.php(82): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#7 C:\xampp\htdocs\bootstrap\cache\compiled.php(2327): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#8 C:\xampp\htdocs\bootstrap\cache\compiled.php(2243): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#9 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#10 {main}  
[2018-03-31 13:34:52] local.INFO:            | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:34:52] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught InvalidArgumentException: View [errors.500] not found. in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 C:\xampp\htdocs\bootstrap\cache\compiled.php(13963): Illuminate\View\FileViewFinder->findInPaths('errors.500', Array)
#1 C:\xampp\htdocs\bootstrap\cache\compiled.php(14091): Illuminate\View\FileViewFinder->find('errors.500')
#2 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(71): Illuminate\View\Factory->make('errors.500', Array)
#3 C:\xampp\htdocs\app\Exceptions\Handler.php(156): Illuminate\Routing\ResponseFactory->view('errors.500', Array, 500)
#4 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(98): App\Exceptions\Handler->convertExceptionToResponse(Object(InvalidArgumentException))
#5 C:\xampp\htdocs\app\Exceptions\Handler.php(82): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(InvalidArgumentException))
#6 C:\xampp\htdocs\bootstrap\cache\compiled.php(2084) in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 {main}  
[2018-03-31 13:35:00] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:35:00] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:35:00] local.ERROR: InvalidArgumentException: View [errors.500] not found. in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 C:\xampp\htdocs\bootstrap\cache\compiled.php(13963): Illuminate\View\FileViewFinder->findInPaths('errors.500', Array)
#1 C:\xampp\htdocs\bootstrap\cache\compiled.php(14091): Illuminate\View\FileViewFinder->find('errors.500')
#2 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(71): Illuminate\View\Factory->make('errors.500', Array)
#3 C:\xampp\htdocs\app\Exceptions\Handler.php(156): Illuminate\Routing\ResponseFactory->view('errors.500', Array, 500)
#4 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(143): App\Exceptions\Handler->convertExceptionToResponse(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#5 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(96): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#6 C:\xampp\htdocs\app\Exceptions\Handler.php(82): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#7 C:\xampp\htdocs\bootstrap\cache\compiled.php(2327): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#8 C:\xampp\htdocs\bootstrap\cache\compiled.php(2243): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#9 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#10 {main}  
[2018-03-31 13:35:00] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:35:00] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught InvalidArgumentException: View [errors.500] not found. in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 C:\xampp\htdocs\bootstrap\cache\compiled.php(13963): Illuminate\View\FileViewFinder->findInPaths('errors.500', Array)
#1 C:\xampp\htdocs\bootstrap\cache\compiled.php(14091): Illuminate\View\FileViewFinder->find('errors.500')
#2 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(71): Illuminate\View\Factory->make('errors.500', Array)
#3 C:\xampp\htdocs\app\Exceptions\Handler.php(156): Illuminate\Routing\ResponseFactory->view('errors.500', Array, 500)
#4 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(98): App\Exceptions\Handler->convertExceptionToResponse(Object(InvalidArgumentException))
#5 C:\xampp\htdocs\app\Exceptions\Handler.php(82): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(InvalidArgumentException))
#6 C:\xampp\htdocs\bootstrap\cache\compiled.php(2084) in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 {main}  
[2018-03-31 13:35:00] local.INFO: ADMIN      | 127.0.0.1     | Teste44  
[2018-03-31 13:35:00] local.INFO: ADMIN      | 127.0.0.1     | Teste5  
[2018-03-31 13:36:34] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:36:34] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:36:34] local.ERROR: InvalidArgumentException: View [errors.500] not found. in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 C:\xampp\htdocs\bootstrap\cache\compiled.php(13963): Illuminate\View\FileViewFinder->findInPaths('errors.500', Array)
#1 C:\xampp\htdocs\bootstrap\cache\compiled.php(14091): Illuminate\View\FileViewFinder->find('errors.500')
#2 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(71): Illuminate\View\Factory->make('errors.500', Array)
#3 C:\xampp\htdocs\app\Exceptions\Handler.php(156): Illuminate\Routing\ResponseFactory->view('errors.500', Array, 500)
#4 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(143): App\Exceptions\Handler->convertExceptionToResponse(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#5 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(96): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#6 C:\xampp\htdocs\app\Exceptions\Handler.php(82): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#7 C:\xampp\htdocs\bootstrap\cache\compiled.php(2327): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#8 C:\xampp\htdocs\bootstrap\cache\compiled.php(2243): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#9 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#10 {main}  
[2018-03-31 13:36:34] local.INFO: ADMIN      | 127.0.0.1     | Ocorreu uma falha no sistema:  
[2018-03-31 13:36:34] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught InvalidArgumentException: View [errors.500] not found. in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 C:\xampp\htdocs\bootstrap\cache\compiled.php(13963): Illuminate\View\FileViewFinder->findInPaths('errors.500', Array)
#1 C:\xampp\htdocs\bootstrap\cache\compiled.php(14091): Illuminate\View\FileViewFinder->find('errors.500')
#2 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(71): Illuminate\View\Factory->make('errors.500', Array)
#3 C:\xampp\htdocs\app\Exceptions\Handler.php(156): Illuminate\Routing\ResponseFactory->view('errors.500', Array, 500)
#4 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(98): App\Exceptions\Handler->convertExceptionToResponse(Object(InvalidArgumentException))
#5 C:\xampp\htdocs\app\Exceptions\Handler.php(82): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(InvalidArgumentException))
#6 C:\xampp\htdocs\bootstrap\cache\compiled.php(2084) in C:\xampp\htdocs\bootstrap\cache\compiled.php:13990
Stack trace:
#0 {main}  
